# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from exploration_manager/DroneState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class DroneState(genpy.Message):
  _md5sum = "44423b0a2449be0e1b2083c475a58ca5"
  _type = "exploration_manager/DroneState"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 drone_id

int8[] grid_ids
float64 recent_attempt_time
float64 stamp

# only used for simulation
float32[] pos
float32[] vel
float32 yaw

# FAME
geometry_msgs/Point goal_posit
int8 role

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['drone_id','grid_ids','recent_attempt_time','stamp','pos','vel','yaw','goal_posit','role']
  _slot_types = ['int32','int8[]','float64','float64','float32[]','float32[]','float32','geometry_msgs/Point','int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       drone_id,grid_ids,recent_attempt_time,stamp,pos,vel,yaw,goal_posit,role

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DroneState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.drone_id is None:
        self.drone_id = 0
      if self.grid_ids is None:
        self.grid_ids = []
      if self.recent_attempt_time is None:
        self.recent_attempt_time = 0.
      if self.stamp is None:
        self.stamp = 0.
      if self.pos is None:
        self.pos = []
      if self.vel is None:
        self.vel = []
      if self.yaw is None:
        self.yaw = 0.
      if self.goal_posit is None:
        self.goal_posit = geometry_msgs.msg.Point()
      if self.role is None:
        self.role = 0
    else:
      self.drone_id = 0
      self.grid_ids = []
      self.recent_attempt_time = 0.
      self.stamp = 0.
      self.pos = []
      self.vel = []
      self.yaw = 0.
      self.goal_posit = geometry_msgs.msg.Point()
      self.role = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.drone_id
      buff.write(_get_struct_i().pack(_x))
      length = len(self.grid_ids)
      buff.write(_struct_I.pack(length))
      pattern = '<%sb'%length
      buff.write(struct.Struct(pattern).pack(*self.grid_ids))
      _x = self
      buff.write(_get_struct_2d().pack(_x.recent_attempt_time, _x.stamp))
      length = len(self.pos)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.pos))
      length = len(self.vel)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.vel))
      _x = self
      buff.write(_get_struct_f3db().pack(_x.yaw, _x.goal_posit.x, _x.goal_posit.y, _x.goal_posit.z, _x.role))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.goal_posit is None:
        self.goal_posit = geometry_msgs.msg.Point()
      end = 0
      start = end
      end += 4
      (self.drone_id,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sb'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.grid_ids = s.unpack(str[start:end])
      _x = self
      start = end
      end += 16
      (_x.recent_attempt_time, _x.stamp,) = _get_struct_2d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.pos = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.vel = s.unpack(str[start:end])
      _x = self
      start = end
      end += 29
      (_x.yaw, _x.goal_posit.x, _x.goal_posit.y, _x.goal_posit.z, _x.role,) = _get_struct_f3db().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.drone_id
      buff.write(_get_struct_i().pack(_x))
      length = len(self.grid_ids)
      buff.write(_struct_I.pack(length))
      pattern = '<%sb'%length
      buff.write(self.grid_ids.tostring())
      _x = self
      buff.write(_get_struct_2d().pack(_x.recent_attempt_time, _x.stamp))
      length = len(self.pos)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.pos.tostring())
      length = len(self.vel)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.vel.tostring())
      _x = self
      buff.write(_get_struct_f3db().pack(_x.yaw, _x.goal_posit.x, _x.goal_posit.y, _x.goal_posit.z, _x.role))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.goal_posit is None:
        self.goal_posit = geometry_msgs.msg.Point()
      end = 0
      start = end
      end += 4
      (self.drone_id,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sb'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.grid_ids = numpy.frombuffer(str[start:end], dtype=numpy.int8, count=length)
      _x = self
      start = end
      end += 16
      (_x.recent_attempt_time, _x.stamp,) = _get_struct_2d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.pos = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.vel = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      _x = self
      start = end
      end += 29
      (_x.yaw, _x.goal_posit.x, _x.goal_posit.y, _x.goal_posit.z, _x.role,) = _get_struct_f3db().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2d = None
def _get_struct_2d():
    global _struct_2d
    if _struct_2d is None:
        _struct_2d = struct.Struct("<2d")
    return _struct_2d
_struct_f3db = None
def _get_struct_f3db():
    global _struct_f3db
    if _struct_f3db is None:
        _struct_f3db = struct.Struct("<f3db")
    return _struct_f3db
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
